name: Build DMG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build DMG
      run: |
        hdiutil create -volname "VoiceInk" -srcfolder "VoiceInk" -ov -format UDZO "VoiceInk.dmg"
